---
apiVersion: v1
kind: Service
metadata:
  namespace: %NAMESPACE%
  name: %STS_NAME%
spec:
  selector:
    app: %STS_NAME%
    tier: %NAMESPACE%
    type: stateful
  type: NodePort
  ports:
  - name: %STS_NAME%-port
    protocol: TCP
    port: 80
    targetPort: 80
